/*
 * Copyright 2022 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package models

import play.api.libs.json.{Json, OFormat}
import uk.gov.hmrc.govukfrontend.views.viewmodels.select.SelectItem
import viewmodels.govuk.select._

final case class Nationality(name: String)

object Nationality {

  implicit val format: OFormat[Nationality] = Json.format

  val allNationalities: Seq[Nationality] = Seq(
    Nationality("Afghan"),
    Nationality("Albanian"),
    Nationality("Algerian"),
    Nationality("American"),
    Nationality("Andorran"),
    Nationality("Angolan"),
    Nationality("Anguillan"),
    Nationality("Argentine"),
    Nationality("Armenian"),
    Nationality("Australian"),
    Nationality("Austrian"),
    Nationality("Azerbaijani"),
    Nationality("Bahamian"),
    Nationality("Bahraini"),
    Nationality("Bangladeshi"),
    Nationality("Barbadian"),
    Nationality("Belarusian"),
    Nationality("Belgian"),
    Nationality("Belizean"),
    Nationality("Beninese"),
    Nationality("Bermudian"),
    Nationality("Bhutanese"),
    Nationality("Bolivian"),
    Nationality("Botswanan"),
    Nationality("Brazilian"),
    Nationality("British"),
    Nationality("British Virgin Islander"),
    Nationality("Bruneian"),
    Nationality("Bulgarian"),
    Nationality("Burkinan"),
    Nationality("Burmese"),
    Nationality("Burundian"),
    Nationality("Cambodian"),
    Nationality("Cameroonian"),
    Nationality("Canadian"),
    Nationality("Cape Verdean"),
    Nationality("Cayman Islander"),
    Nationality("Central African"),
    Nationality("Chadian"),
    Nationality("Chilean"),
    Nationality("Chinese"),
    Nationality("Citizen of Antigua and Barbuda"),
    Nationality("Citizen of Bosnia and Herzegovina"),
    Nationality("Citizen of Guinea - Bissau"),
    Nationality("Citizen of Kiribati"),
    Nationality("Citizen of Seychelles"),
    Nationality("Citizen of the Dominican Republic"),
    Nationality("Citizen of Vanuatu"),
    Nationality("Colombian"),
    Nationality("Comoran"),
    Nationality("Congolese (Congo)"),
    Nationality("Congolese (DRC)"),
    Nationality("Cook Islander"),
    Nationality("Costa Rican"),
    Nationality("Croatian"),
    Nationality("Cuban"),
    Nationality("Cymraes"),
    Nationality("Cymro"),
    Nationality("Cypriot"),
    Nationality("Czech"),
    Nationality("Danish"),
    Nationality("Djiboutian"),
    Nationality("Dominican"),
    Nationality("Dutch"),
    Nationality("East Timorese"),
    Nationality("Ecuadorean"),
    Nationality("Egyptian"),
    Nationality("Emirati"),
    Nationality("English"),
    Nationality("Equatorial Guinean"),
    Nationality("Eritrean"),
    Nationality("Estonian"),
    Nationality("Ethiopian"),
    Nationality("Faroese"),
    Nationality("Fijian"),
    Nationality("Filipino"),
    Nationality("Finnish"),
    Nationality("French"),
    Nationality("Gabonese"),
    Nationality("Gambian"),
    Nationality("Georgian"),
    Nationality("German"),
    Nationality("Ghanaian"),
    Nationality("Gibraltarian"),
    Nationality("Greek"),
    Nationality("Greenlandic"),
    Nationality("Grenadian"),
    Nationality("Guamanian"),
    Nationality("Guatemalan"),
    Nationality("Guinean"),
    Nationality("Guyanese"),
    Nationality("Haitian"),
    Nationality("Honduran"),
    Nationality("Hong Konger"),
    Nationality("Hungarian"),
    Nationality("Icelandic"),
    Nationality("Indian"),
    Nationality("Indonesian"),
    Nationality("Iranian"),
    Nationality("Iraqi"),
    Nationality("Irish"),
    Nationality("Israeli"),
    Nationality("Italian"),
    Nationality("Ivorian"),
    Nationality("Jamaican"),
    Nationality("Japanese"),
    Nationality("Jordanian"),
    Nationality("Kazakh"),
    Nationality("Kenyan"),
    Nationality("Kittitian"),
    Nationality("Kosovan"),
    Nationality("Kuwaiti"),
    Nationality("Kyrgyz"),
    Nationality("Lao"),
    Nationality("Latvian"),
    Nationality("Lebanese"),
    Nationality("Liberian"),
    Nationality("Libyan"),
    Nationality("Liechtenstein citizen"),
    Nationality("Lithuanian"),
    Nationality("Luxembourger"),
    Nationality("Macanese"),
    Nationality("Macedonian"),
    Nationality("Malagasy"),
    Nationality("Malawian"),
    Nationality("Malaysian"),
    Nationality("Maldivian"),
    Nationality("Malian"),
    Nationality("Maltese"),
    Nationality("Marshallese"),
    Nationality("Martiniquais"),
    Nationality("Mauritanian"),
    Nationality("Mauritian"),
    Nationality("Mexican"),
    Nationality("Micronesian"),
    Nationality("Moldovan"),
    Nationality("Monegasque"),
    Nationality("Mongolian"),
    Nationality("Montenegrin"),
    Nationality("Montserratian"),
    Nationality("Moroccan"),
    Nationality("Mosotho"),
    Nationality("Mozambican"),
    Nationality("Namibian"),
    Nationality("Nauruan"),
    Nationality("Nepalese"),
    Nationality("New Zealander"),
    Nationality("Nicaraguan"),
    Nationality("Nigerian"),
    Nationality("Nigerien"),
    Nationality("Niuean"),
    Nationality("North Korean"),
    Nationality("Northern Irish"),
    Nationality("Norwegian"),
    Nationality("Omani"),
    Nationality("Pakistani"),
    Nationality("Palauan"),
    Nationality("Palestinian"),
    Nationality("Panamanian"),
    Nationality("Papua New Guinean"),
    Nationality("Paraguayan"),
    Nationality("Peruvian"),
    Nationality("Pitcairn Islander"),
    Nationality("Polish"),
    Nationality("Portuguese"),
    Nationality("Prydeinig"),
    Nationality("Puerto Rican"),
    Nationality("Qatari"),
    Nationality("Romanian"),
    Nationality("Russian"),
    Nationality("Rwandan"),
    Nationality("Salvadorean"),
    Nationality("Sammarinese"),
    Nationality("Samoan"),
    Nationality("Sao Tomean"),
    Nationality("Saudi Arabian"),
    Nationality("Scottish"),
    Nationality("Senegalese"),
    Nationality("Serbian"),
    Nationality("Sierra Leonean"),
    Nationality("Singaporean"),
    Nationality("Slovak"),
    Nationality("Slovenian"),
    Nationality("Solomon Islander"),
    Nationality("Somali"),
    Nationality("South African"),
    Nationality("South Korean"),
    Nationality("South Sudanese"),
    Nationality("Spanish"),
    Nationality("Sri Lankan"),
    Nationality("St Helenian"),
    Nationality("St Lucian"),
    Nationality("Stateless"),
    Nationality("Sudanese"),
    Nationality("Surinamese"),
    Nationality("Swazi"),
    Nationality("Swedish"),
    Nationality("Swiss"),
    Nationality("Syrian"),
    Nationality("Taiwanese"),
    Nationality("Tajik"),
    Nationality("Tanzanian"),
    Nationality("Thai"),
    Nationality("Togolese"),
    Nationality("Tongan"),
    Nationality("Trinidadian"),
    Nationality("Tristanian"),
    Nationality("Tunisian"),
    Nationality("Turkish"),
    Nationality("Turkmen"),
    Nationality("Turks and Caicos Islander"),
    Nationality("Tuvaluan"),
    Nationality("Ugandan"),
    Nationality("Ukrainian"),
    Nationality("Uruguayan"),
    Nationality("Uzbek"),
    Nationality("Vatican citizen"),
    Nationality("Venezuelan"),
    Nationality("Vietnamese"),
    Nationality("Vincentian"),
    Nationality("Wallisian"),
    Nationality("Welsh"),
    Nationality("Yemeni"),
    Nationality("Zambian"),
    Nationality("Zimbabwean")
  )

  val selectItems: Seq[SelectItem] =
    SelectItem(value = None, text = "Select a nationality") +:
      allNationalities.map {
        nationality =>
          SelectItemViewModel(
            value = nationality.name,
            text  = nationality.name
          )
      }
}
